config/routes.rb
Playgrounds::Application.routes.draw do
  resources :playgrounds

  root 'playgrounds#index'

  

end

app/models/playground.rb
class Playground < ActiveRecord::Base

  SPORTS = ['Football','Cricket','Field Hockey','Tennis','Volleyball','Table Tennis','Baseball','Golf','American Football']

  acts_as_gmappable :process_geocoding => false
  
  validates_inclusion_of :sport, :in => Playground::SPORTS
  validates_presence_of :name

  # *** Server-side reverse geocoding, not for this example!
  #reverse_geocoded_by :latitude, :longitude do |obj,results|
  #  if geo = results.first
  #    obj.city    = geo.city
  #    obj.postal_code = geo.postal_code
  #    obj.country = geo.country_code
  #    obj.route = geo.address
  #  end
  #end
    
  #after_validation :reverse_geocode  

  #def address=(address)
  #end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  
  before_action :set_playground, only: [:show, :edit, :update, :destroy]
  
  respond_to :html
  
  # 404
  rescue_from ActiveRecord::RecordNotFound do |exception| 
    rescue_record_not_found(exception)
  end

  # GET /playgrounds
  # GET /playgrounds.json
  def index
    @playgrounds = Playground.all
    @json = @playgrounds.to_gmaps4rails do |playground, marker|
      @playground = playground
      marker.infowindow render_to_string(:action => 'show', :layout => false)    
      marker.json({ :id => @playground.id })
    end
  end

  # GET /playgrounds/1
  # GET /playgrounds/1.json
  def show
    respond_with(@playground, :layout =>  !request.xhr?)
  end

  # GET /playgrounds/new
  def new
    @playground = Playground.new(params[:playground].present? ? playground_params : nil)
    respond_with(@playground, :layout => !request.xhr?)
  end

  # GET /playgrounds/1/edit
  def edit
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  # POST /playgrounds
  # POST /playgrounds.json
  def create
    @playground = Playground.new(playground_params)
    respond_to do |format|
      if @playground.save
        format.html { redirect_to @playground, notice: 'Playground was successfully created.' }
        format.js {}
      else
        format.html { render action: 'new' }
        format.js {}      
      end
    end
  end

  # PATCH/PUT /playgrounds/1
  # PATCH/PUT /playgrounds/1.json
  def update
    respond_to do |format|
      if @playground.update(playground_params)
        format.html { redirect_to @playground, notice: 'Playground was successfully updated.' }
        format.js {}  
      else
        format.html { render action: 'edit' }
        format.js {}  
      end
    end
  end

  # DELETE /playgrounds/1
  # DELETE /playgrounds/1.json
  def destroy
    @playground.destroy
    respond_to do |format|
      format.html { redirect_to playgrounds_url }
      format.js {}  
    end
  end


private
  # Use callbacks to share common setup or constraints between actions.
  def set_playground
    @playground = Playground.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playground_params
    params.require(:playground).permit(:name, :sport, :latitude, :longitude, :street_number, :route, :city, :country, :postal_code)
  end
  
  # Generic not found action
  def rescue_record_not_found(exception)
    respond_to do |format|
      format.html
      format.js { render :template => "playgrounds/404.js.erb", :locals => {:exception => exception} }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # eat it!
  def comment(&block)
  end
  
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Playgrounds</title>
      <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato:400,700' %>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
    </head>
    <body>

        <div class="container-fluid">

            <div class="row-fluid">
            
            </div>

            <div class="row-fluid">
                <div class="span9">
                    <%= yield %>           
                </div>
            
                <div class="span3"> 
                    
                    <div id="contextual-panel">
                        <%= yield :contextual %>
                    </div>
               
                </div>
            </div>
        </div>

        <%= yield :scripts %>

    </body>
</html>

app/views/playgrounds/404.js.erb
<% if params[:id] %>
    // Clear the marker itself
    clearMarkerById(<%=params[:id]%>);
    alert_user("<%= j(raw(exception.message)) %>. I'd better remove that...", "alert-error");
<%else%>  
    // notify user
    alert_user("<%= j(raw(exception.message)) %>", "alert-error");
<%end%>

// Close infowindow
closeInfowindow();

app/views/playgrounds/_create_side.html.erb
<h2>A newly created place</h2>

<div id="alert_placeholder"></div>    

<p>You can now edit or destroy the new marker by <strong>clicking on it</strong></p>
<p>The same can be said on existing markers, though their behaviour comes from the server</p>

app/views/playgrounds/_destroy_side.html.erb
<h2>Destroy details</h2>

<div id="alert_placeholder"></div>    

<p>Once deleted the marker is removed from the database and from the map front-end</p>

app/views/playgrounds/_form.html.erb
<%= form_for @playground, :html => { :id => 'playground_form' }, :remote => true do |f| %>

  <% if @playground.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playground.errors.count, "error") %> prohibited this playground from being saved:</h2>

      <ul>
      <% @playground.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.select(:sport, Playground::SPORTS, {:include_blank => h('<Please select sport>')}) %>
  </div>
  
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <%= f.hidden_field :street_number %>
  <%= f.hidden_field :route %>
  <%= f.hidden_field :city %>
  <%= f.hidden_field :country %>
  <%= f.hidden_field :postal_code %>
  
  <%= f.submit class: "btn btn-lg btn-primary" %>
  
<% end %>

app/views/playgrounds/_home_side.html.erb
<h2>Hey user!</h2>

<div id="alert_placeholder"></div>    

<p>Welcome to this <em>gmaps4rails <strong>CRUD</strong> demo</em></p>     

<p>Please allow the browser to send your location</p>     

<p><strong>Double click</strong> over the map and a form will popup to create a new place.</p>
<p>If you have opened a create form you can still dissmiss the form by clicking on close. The 
    same happens when double clicking over a different spot</p>
<p>You can also <strong>click on an existing spot</strong> to delete or modify it</p>

app/views/playgrounds/_update_side.html.erb
<h2>Updated... and now?</h2>

<div id="alert_placeholder"></div>    

<p>Please note that this actions updates <strong>the click event</strong> for the marker with the new content,
    along with the database</p>

<p>You can also test errors letting the sport or name field empty</p>

app/views/playgrounds/create.js.erb
<%if (@playground.errors.empty?) %>    
    
    var createMarkerWithInfoWindow = function () {
    
        // Remove previous marker
        clearMarker(playgroundsNewMarker);

        // Create marker info
        var markerInfo = {    
            position: new google.maps.LatLng(
                    <%=@playground.latitude%>,
                    <%=@playground.longitude%>
            ), 
            map: Gmaps.map.serviceObject,
            id: <%=@playground.id%>
        }
            
        // Create new marker
        var marker = new google.maps.Marker(markerInfo);
    
        // Add marker serviceObject
        markerInfo.serviceObject = marker;
    
        // Add to the markers array
        Gmaps.map.markers.push(markerInfo);

        // On click open infowindow
        google.maps.event.addListener(marker, "click", function (e) {
            openInfowindow(
                "<%= j(render :template => 'playgrounds/show.html.erb', 
                              :locals  => { :playground => @playground}) %>", 
                marker
            )
        });
        
        // New pane content
        $("#contextual-panel").html("<%=j(render :partial => 'create_side') %>");
    
    
        // Notify user
        alert_user("Got it. A new playground has been added!","alert-info");
       
    }    
    
    // Invoke it
    createMarkerWithInfoWindow();
    

<%else%>

    // Notify user
    alert_user("Aj Got :(... I can't insert that. <%= j(raw(@playground.errors.full_messages.join(','))) %>", "alert-error");

<%end%>

app/views/playgrounds/destroy.js.erb
// Clear the marker itself
clearMarkerById(<%=@playground.id%>);

// Close infowindow
closeInfowindow();

// Change the pane
$("#contextual-panel").html( "<%=j(render :partial => 'destroy_side') %>");

// Notify
alert_user("Destroyed a playground in tha neighborhood!", "alert-info");

app/views/playgrounds/edit.html.erb
<%= render 'form' %>

app/views/playgrounds/edit.js.erb
// Open the edit form
openInfowindow(
    "<%= j(render :template => 'playgrounds/edit.html.erb', :locals  => {:playground => @playground}) %>", 
    findById(<%=@playground.id%>)
);           

app/views/playgrounds/index.html.erb
<%= stylesheet_link_tag "gmaps4rails" %>

<%= gmaps(:markers => {
            :data => @json,        
          }, 
          :map_options => {
            :do_clustering => false, 
            :disableDoubleClickZoom => true,
            :detect_location => true,       
            :center_on_user  => true,        
            :zoom => 6,
            :auto_adjust => false
          }
) %>

<%= content_for :scripts do %>
    <script>
        // Document ready stuff
        $(document).ready(function() {
            // Bizarre ajax errors
            $(document).bind("ajaxError", function() {
                alert_user('There was an error processing your request. Please try again later', 'alert-error');
            });
        });

        // Instance geocoder
        var geocoder = new google.maps.Geocoder();

        // New marker beacon
        var playgroundsNewMarker = null;

        // Google maps map-related events
        Gmaps.map.callback = function() {

            // Double click event to show new marker form
            google.maps.event.addListener(Gmaps.map.serviceObject, 'dblclick', function(event) {            
    
                // Remove previous marker when adding a new one
                clearMarker(playgroundsNewMarker);
    
                // Geocode point. Callback on success will show the creation form
                geocodePoint(event.latLng, function(data) {
                   playgroundsNew(data);
                });                
            });
        }; 
    </script>
<% end %>

<% content_for :contextual do %>
    <%=render :partial => 'home_side' %>
<% end %>

app/views/playgrounds/new.html.erb
<%= render 'form' %>

app/views/playgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong> 
  <%= @playground.name %>
</p>

<p>
  <strong>Sport:</strong> 
  <%= @playground.sport %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @playground.street_number %>
</p>
<p>
  <strong>Route:</strong>
  <%= @playground.route %>
</p>
<p>
  <strong>City:</strong>
  <%= @playground.city %>
</p>
<p>
  <strong>Country:</strong>
  <%= @playground.country %>
</p>
<p>
  <strong>Postal code:</strong>
  <%= @playground.postal_code %>
</p>

<%= link_to 'Edit', edit_playground_path(@playground), class: "btn btn-lg btn-primary", :remote =>true  %>
<%= link_to raw('Destroy <i class="icon-trash"></i>'), @playground, class: "btn btn-lg", method: "delete", data: { confirm: 'Are you sure?' }, :remote =>true %>

app/views/playgrounds/update.js.erb
<%if (@playground.errors.empty?) %>    

    var updateMarkerWithInfowindow = function () { 

        // Get marker
        var marker_to_update = findById(<%=@playground.id%>);

        // Newly updated infowindow behaviour
        var showUpdatedInfowinow = function() {
            openInfowindow(
                "<%= j(render :template => 'playgrounds/show.html.erb', 
                              :locals  => {:playground => @playground}) %>", 
                marker_to_update
            )
        };

        // Open the new window
        showUpdatedInfowinow();

        // Update click behaviour from now on to open this new infowindow
        google.maps.event.addListener(marker_to_update, "click", function (e) {
            showUpdatedInfowinow();
        });     
        
        // Change the pane
        $("#contextual-panel").html( "<%=j(render :partial => 'update_side') %>" );
    
        // Notify user    
        alert_user("Yap! You updated it correctly","alert-info");
    }
    
    // Invoke it
    updateMarkerWithInfowindow();  
      
<%else%>

    // Notify user
    alert_user("Errr, well, I could not update that. <%= j(raw(@playground.errors.full_messages.join(','))) %>","alert-error");

<%end%>